### PR TITLE
Fixes #406

### LINKED ISSUE #406: Deployment disappears upon restarting vscode (issue vscode-adapters #362)
@adietish noted:

Steps:

    ASSERT: have a server (ex. wildfly 16)
    EXEC: add a deployment to it (ex. wildfly quickstarts/kitchensink, exploded war in target/kitchensink)
    ASSERT: deployment is listed as child node to your server in "Servers" view
    ASSERT: wait for it to get published (Autopublisher)
    EXEC: quit and restart vscode

Result:
Deployment is not listed any more, there's no child node to your server any more.
Nevertheless if one restarts the server (it was terminated when vscode was quit) and then looks at the server log, one can still see it being deployed to the server

### PR DESCRIPTION
**Pull request by redking00**
Fixes issue 362 in vscode-adapters

### CODE REVIEW

**Comment by robstryker** [comment]
Hey, I really want to accept this patch, but, I need an explanation of what is going wrong and how this fixes it exactly. A unit test would be ideal (not an integration test but a simple unit test), but even an explanation of what's going wrong here with some json examples would help me out a lot. 

Can you provide more color on exactly how this is failing?

**Comment by robstryker** [comment]
Seems there's an NPE:


java.lang.NullPointerException
	at org.jboss.tools.rsp.launching.memento.JSONMemento.getString(JSONMemento.java:112)
	at org.jboss.tools.rsp.server.model.internal.Server.loadState(Server.java:132)
	at org.jboss.tools.rsp.server.core.internal.Base.load(Base.java:346)
	at org.jboss.tools.rsp.server.core.internal.Base.loadFromFile(Base.java:432)
	at org.jboss.tools.rsp.server.model.internal.Server.load(Server.java:196)
	at org.jboss.tools.rsp.server.model.ServerModel.loadServer(ServerModel.java:183)
	at org.jboss.tools.rsp.server.model.ServerModel.loadServers(ServerModel.java:173)
	at org.jboss.tools.rsp.server.model.ServerModel.loadServers(ServerModel.java:165)
	at org.jboss.tools.rsp.server.model.ServerPersistenceManager.loadState(ServerPersistenceManager.java:92)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.launch(ServerManagementServerLauncher.java:71)
	at org.jboss.tools.rsp.server.wildfly.impl.WildflyServerMain.launch(WildflyServerMain.java:30)
	at org.jboss.tools.rsp.server.ServerManagementServerLauncher.launch(ServerManagementServerLauncher.java:67)
	at org.jboss.tools.rsp.server.wildfly.impl.WildflyServerMain.main(WildflyServerMain.java:23)

**Comment by robstryker** [comment]
If you run the server with logging flags, you can see the error:   java -Drsp.log.level=4 -jar bin/felix.jar

**Comment by redking00** [comment]
Sorry for the lack of explanation. As you could see, it was an NPE caused by misuse of the IMemento api processing the deployment options. Thanks for accepting the patch, I use vscode-adapters and I'm glad to contribute.

**Comment by robstryker** [comment]
I added a unit test for this functionality:   https://github.com/redhat-developer/rsp-server/commit/c3083cf3645e257daea11b1ebc44d23d052d0caa

Thanks for the contribution! Glad to see someone using this!

Feel free to let me know any features you think are missing!

**Pull request merged**
