### PR TITLE
Running tests on jdk 1.8 and 11

### PR DESCRIPTION
**Pull request by odockal**
- refactor pipeline in declarative way
   - collect test results properly and make pipeline visualization clear

Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
I am waiting for https://redhat.service-now.com/surl.do?n=PNT0489021 to be done. Once when Jenkins is upgraded we can start using given syntax of parallel branches being run on one node.

**Comment by odockal** [comment]
Ticket resolved. Jenkins upgraded and so is new pipeline.

**Comment by odockal** [comment]
Should be merged after #266.

**Comment by adietish** [comment]
@odockal I have no means to verify this. Can anyone in QE do that, please?

**Comment by odockal** [comment]
@adietish Anyone in QE is only @jrichter1, so we can ask him.

**Comment by odockal** [comment]
testPR

**Comment by adietish** [comment]
@jrichter1 could you please review this?

**Comment by jrichter1** [comment]
Don't worry, I'm pestering @odockal about this already.
It seems from the latest test runs that java 11 build is failing though. @adietish can you check this out?
(https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Adapters/view/Playground/job/rsp-pipeline/97/)

**Comment by odockal** [comment]
@jrichter1 @adietish Strange, I am fine running it locally on fedora with openjdk11...

**Comment by adietish** [comment]
@odockal @jrichter1 I can run this PR fine using 1.8 or 11 locally. Build is green, too. So we're ready to merge this, right?

**Comment by adietish** [comment]
merging this would lead to failing integration tests given that our ITs wont run with jdk11: #277

**Comment by odockal** [comment]
@adietish  @jrichter1  We are green guys: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Adapters/view/Playground/job/rsp-pipeline/107/

**Comment by odockal** [comment]
@jrichter1 Seems like pipeline is green: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/rsp-build_parametrized/detail/rsp-build_parametrized/52/pipeline

**Pull request merged**
