### PR TITLE
Fix tests for optional attributes

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

### CODE REVIEW

**Comment by robstryker** [comment]
testPR

**Comment by robstryker** [comment]
testPR

**Comment by odockal** [comment]
I believe that we can close this PR as its parts were merged in other PRs?

**Comment by adietish** [comment]
@odockal nice catch! You're right. 
On a sidenode, all these hand crafted complicated comparisons of keys/values in a map is something that assertj provides out-of-the-box.

**Comment by odockal** [comment]
@adietish  No in this case I believe. We needed to compare values based on the type that is not derived from the variable itself but based on another field that defined the compared variable's type. Other than that, equals method was defined for underlying objects and worked in most cases, but there was conversion of int to double in json rpc which we could not influence as Rob described in another PR. (Roughly saying)...

**Pull request closed without merging**
