### PR TITLE
Refactor itests to use any wildfly server

### PR DESCRIPTION
**Pull request by odockal**
- add wildfly-14 and wildfly-15 profiles
- profile wildfly-14 is activated by default
- profile wf15 is activated by setting sys. prop. -Dwildfly-15

Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
testPR

**Comment by adietish** [comment]
when running this PR on the cmd line via ```mvn clean verify -Dintegration-tests``` I have 1 test failure:
```
Results :

Failed tests:   testStopServer(org.jboss.tools.rsp.itests.wildfly.WildFlyLaunchingTest): Waiting for server state to change to started timed out
  testStartServer(org.jboss.tools.rsp.itests.wildfly.WildFlyPublishingTest): Waiting for server state to change to a non-null value
```

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@adietish As of disabled download progress, we can use mvn -B variable. It means batch mode. What java are you using for the run?

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
testPR

**Comment by adietish** [comment]
@odockal great, ```-B``` helps, no download progress polluting the output. And as you pointed out, here's an issue in maven-download-plugin opened: https://github.com/maven-download-plugin/maven-download-plugin/issues/101

**Comment by adietish** [comment]
turns out that master has the exact same failures for me on Mac. In other words, the failures are not caused by this PR.
Current state of the integration tests in jenkins is green, when running on rhel7 or win10 (mac is missing). I other terms, I'll +1 this issue and create an issue about the mac specific problems of the integration tests.

**Comment by adietish** [comment]
I filed #272 as mac specific failures when running the integration tests.

**Comment by odockal** [comment]
@adietish Super, thanks!

**Pull request merged**
