### PR TITLE
Add Integration Tests

### PR DESCRIPTION
**Pull request by jrichter1**
A bunch of tests to verify the API functionality.
Also adds equals/hashcode to some data objects (it's hard to call contains on collections without them).

### CODE REVIEW

**Comment by robstryker** [comment]
I'm not against these tests in principle... I'm just very curious why they need to be in a new folder called integration-tests.  Half of these tests clearly belong in the server-wildfly section. The other half are more generic utility classes which could go in the normal server/ section, in one of the bundles there. 

Some of the classes here look very very similar to classes that already exist in the existing test cases.

**Comment by jrichter1** [comment]
Well, these are not meant to test classes (leave that to the unit tests), but rather the API.

The point of a separate module is these tests actually use the packaged rsp distribution to test against. For that it first needs to be built, and since it's naturally the last module in the chain, the other modules' tests just wouldn't have access to it.

Plus it doesn't really matter what runtime is used in the tests. It might as well use any other supported server. Or it should use all of them at some point.

**Comment by jrichter1** [comment]
Rebased, also used the itests module to run code coverage.

**Comment by robstryker** [comment]
I verified that all the .equals stuff doesn't somehow mess up my generation of the spec. Seems ok. I might try to move these into the distribution module in some fashion, but I'm not 100% sure yet.

**Pull request merged**
