### PR TITLE
[187] use updated API to identify clients

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

This PR will fail until another release of lsp4j.jsonrpc. 

But I'm pretty sure it works! (I have no idea if it works ;) )

### CODE REVIEW

**Comment by jkopriva** [comment]
@robstryker Can you please rebase? I have added sonar profile in pom.xml and PR check job.

**Comment by robstryker** [comment]
No point in rebasing it until the actual libs are released and are consumable.

**Comment by robstryker** [comment]
testPR

**Comment by robstryker** [comment]
testPR

**Pull request merged**
