### PR TITLE
added test for RuntimesInstallerModel

### PR DESCRIPTION
**Pull request by adietish**
Signed-off-by: Andre Dietisheim <adietish@redhat.com>

### CODE REVIEW

**Comment by adietish** [comment]
found issues #197 and #198 when writing the tests.

**Comment by adietish** [comment]
the build is failing bcs ```org.jboss.tools.rsp.runtime.core.model.internal.DownloadRuntimesModel``` is not being exported by the ```org.jboss.tools.rsp.runtime.core``` bundle. 
To fix this we have either to export the model (so that it gets testable by the test bundle) or turn the test bundle into a fragment. 
@robstryker @jeffmaury Thoughts?

**Comment by adietish** [comment]
@jeffmaury unfortunately this isn't possible for felix. The ```x-friends``` directive is only available in equinox since it isn't specified in the osgi standard api (see here: https://www.osgi.org/bundle-headers-reference/ , it's specified by the Eclipse foundation, not the OSGI Alliance).

**Comment by jeffmaury** [comment]
But our tests are not run by Felix but Equinox :)

**Comment by adietish** [comment]
@jeffmaury true, but using x-friends, which only equinox would respect would not be helpful: the internal package would exported without restrictions when running on felix while it would be exported with restrictions and cause API warning when running the tests. 
Am I missing something?

**Comment by robstryker** [comment]
@adietish  is correct, exporting with x-friends would still leave the packages exported for other containers. However, it would serve as a documentation that despite being exported and technically available for import, these packages are not INTENDED to be consumed by clients. So x-friends could still be a valid solution, but not my favorite for this specific issue here. 

Fragments are the better way to go in general if one wants to be absolutely osgi-correct. But this feels like more work and I'm less familiar with fragments, so I kinda hate them. 

As it turns out, there's a better solution:  RuntimeCoreActivator has a method public static IDownloadRuntimesModel createDownloadRuntimesModel()  which can be used in testing. 

Other problems that arose during review of this patch is that many efforts were made to extend internal classes to override one method which was protected instead of public. This could also be solved by simply evaluating whether that method should be part of the interface or not. In many cases, they could, which removes lots of these issues. 

Finally, I experienced some final problems running the build after the above changes: mocks were incomplete or not correctly stubbed. It turns out, there's no real reason to use mocks for these classes. The model classes themselves are perfectly sufficient and can be tested standalone via instantiation or subclassing only. No need for mocking. 

I opened a new PR:  https://github.com/redhat-developer/rsp-server/pull/200   which has 1 additional commit to fix these issues. Since andre is on PTO, I'll just go ahead and approve these changes, with my additional commit. I'll make sure not to squash them, so @adietish  gets his credit ;)

**Comment by robstryker** [comment]
These 3 commits have been merged. See https://github.com/redhat-developer/rsp-server/pull/200

**Pull request closed without merging**
