### PR TITLE
Implementing itests and patching Update server API function call

### LINKED ISSUE #441: Implement itests for missing API functions - Edit Server
Api functions: getServerAsJson and updateServer

Changes made in https://github.com/redhat-developer/rsp-server/commit/ffdfa74800745ca413f5c2bb7a84195d53f844fa#diff-8a5da52ed126447d359e70c05721a8aa.

### LINKED ISSUE #463: Passing null update server request in update server call breaks the server

### LINKED ISSUE #465: Unhandled state of server when passing invalid/null server type in server handle as a request to update server
Example:
```
		// test invalid server type in handle
		inHandle = new ServerHandle(SERVER_ID,
				new ServerType("some.id", "my.server", "Random server type definition"));
		request.setHandle(inHandle);
		response = serverProxy.updateServer(request).get(REQUEST_TIMEOUT, TimeUnit.MILLISECONDS);
```

### PR DESCRIPTION
**Pull request by odockal**
Add Edit server itests (fixes #441)
Add null check for update server request (fixes #463)
Add check for invalid server type in request' handle (fixes #465)

### CODE REVIEW

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
testPR

**Comment by robstryker** [comment]
@odockal  Can you verify this patch works? Sonar doesn't seem to be liking it much for some reason.

**Comment by robstryker** [comment]
Looks good on review I guess. Build likes it. Only sonar has a problem. Oh well.

**Pull request merged**
