### PR TITLE
Fix itests failures

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by adietish** [comment]
@odockal I see 4 tests failing in (jenkins build 614)[https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rsp-server-prcheck-matrix/614/]: 
```
org.jboss.tools.rsp.itests.wildfly.WildFlyServerModelTest.testGetOptionalAttributes
org.jboss.tools.rsp.itests.wildfly.WildFlyServerModelTest.testGetOptionalAttributes
org.jboss.tools.rsp.itests.wildfly.WildFlyServerModelTest.testGetOptionalAttributes
org.jboss.tools.rsp.itests.wildfly.WildFlyServerModelTest.testGetOptionalAttributes
```

**Comment by adietish** [comment]
testPR

**Comment by odockal** [comment]
@adietish Well, I believe that test is alright, but there is a bug more likely. Test excepts to get attribute with variable that contains integer value, but it got double. Value is ok, but the type is not. What is more strange is that the the test had no assert since last update. So the assert is back but the issue is still there.

**Comment by robstryker** [comment]
The json library will by default send integers as doubles. We have utility methods in several locations that try to work around this by storing the expected type and the json-transferred type and make sure we get the proper type back.... but it's possible that either we have missed a place where this is required, or that your test is testing the lower APIs and are analyzing the directly-transferred data. 

the rsp-server repo's cli has for example the following code:

	/*
	 * Conversion
	 */
	public Object workaroundDoubles(Object defaultVal, String attrType) {

		// Workaround for the problems with json transfer
		Class<?> intended = getAttributeTypeAsClass(attrType);
		if (Integer.class.equals(intended) && Double.class.equals(defaultVal.getClass())) {
			return Integer.valueOf(((Double)defaultVal).intValue());
		}
		return defaultVal;
	}

**Comment by odockal** [comment]
I am testing API itself using client calls. I do not think it is lower testing of transmitted data. That dummy client extends ServerManagementClientImpl which could be quite high in hierarchy, right? I believe that we are missing conversion back to ints from doubles.

**Comment by robstryker** [comment]
Conversion is not automatic. The client must do it themselves.  In my case, that means the CLI classes. In your case, that means the test classes. Your test classes should not be failing over an int/double issue. 

BTW this test doesn't even seem to do anything?   It seems to make an actual request and get the list of optional attributes, then it loads a map with expected values, and then...  nothing? It doesn't even attempt to compare them? I'm a bit confused what this test is doing.

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/411/files#diff-fbe6257fe500d4fe0fadb91eb3550b0bR131

Look here: I have changed the asserts to ignore a double to int failure. Why? Because the json libraries give me doubles when I want ints. It is our job to do that conversion. We do not have the ability to do that conversion in any included library or in any logic before your client gets the data. 

You may believe my client / dummy client should be doing that for you and your tests should be cleaner. Unfortunately we cannot. All clients must take time to disambiguate the int / double situation. The protocol does not make it clear which one is desired. Thats why my Attribute objects have to include hte type... otherwise I wouldn't know what to convert it back to. 

There's no way to fix this at a lower level. Sorry.

**Comment by odockal** [comment]
What you are saying makes perfect sense, so I definitely agree then. 

The test was not asserting anything that's why I made this PR so it started doing something. now, I would change it, so it would not just simply assert attributes objects via equals, but rather checking object values.

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@robstryker I have combined your proposed fix with my PR. Difference is that I manually define attributes that server should contain in oppose to your approach getting them from the mock server. Hope you don't mind.

**Comment by robstryker** [comment]
I'll merge it, but I don't really like the approach.  Whenever we add an attribute we'll need to update tests. Maybe that's better... idk.

**Pull request merged**
