### PR TITLE
Add timeout to api get calls to avoid long waiting (fixes #414)

### LINKED ISSUE #414: Set up timeout limit for api get calls in integration tests to avoid endless waiting

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by robstryker** [comment]
To be clear, this patch is for integration tests only.

**Comment by odockal** [comment]
@robstryker that's right, itests only. I increased timeout a bit, so let's check it out.

**Comment by odockal** [comment]
testPR

**Comment by jrichter1** [comment]
testPR

**Comment by odockal** [comment]
@jrichter1 Build passed. Good to go?

**Comment by robstryker** [comment]
testPR

**Comment by robstryker** [comment]
let's just try it once more to see if it's really fixed ;)

**Comment by odockal** [comment]
Sure thing. Still looks good :)

**Comment by robstryker** [comment]
java.lang.AssertionError
	at org.jboss.tools.rsp.server.model.publishing.AutoPublishThreadTest.testImmediateStoppedAndNoneState(AutoPublishThreadTest.java:84)

Not pushing this until you show me your test can run! Or unless you prove a bug in my code :|

**Comment by odockal** [comment]
@robstryker  Well... integration tests have run successfully and it was the only thing updated, no chance to introduce new bug to unit tests. ;) What you are seeing, is failing unit test and it happened that it failed on windows only. 

Itests run on rhel7: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rsp-server-prcheck-matrix/711/label=rhel7/testReport/org.jboss.tools.rsp.itests.wildfly/

On windows we cannot see itests cause unit tests failed, so itests were not run. I am rerunning the build once more. Let's see how that will go.

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
testPR

**Pull request merged**
