### PR TITLE
Wildfly server 15 as default (fixes #277)

### LINKED ISSUE #277: integration-tests: fail when running with jdk11
1. ASSERT: make sure that you're using jdk11
2. `mvn clean verify -Pintegration-tests`

Result:
```
Failed tests:   testStartServerTwice(org.jboss.tools.rsp.itests.wildfly.WildFlyLaunchingTest): Waiting for server state to change to started timed out
  testStartServer(org.jboss.tools.rsp.itests.wildfly.WildFlyLaunchingTest): Waiting for server state to change to started timed out
  testStartServer(org.jboss.tools.rsp.itests.wildfly.WildFlyPublishingTest): Waiting for server state to change to a non-null value
```

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
Fixes #277.

**Comment by adietish** [comment]
@odockal I see it running wildfl15, which is good. But then I see the following 2 tests failing consistently - which might be unrelated to your change: 
```
[ERROR] Failures:
[ERROR] org.jboss.tools.rsp.itests.wildfly.WildFlyPublishingTest.testStartServer(org.jboss.tools.rsp.itests.wildfly.WildFlyPublishingTest)
[ERROR]   Run 1: WildFlyPublishingTest.testStartServer:93->waitForNonNullServerState:169 Waiting for server state to change to a non-null value
[ERROR]   Run 2: WildFlyPublishingTest.testStartServer:93->waitForNonNullServerState:169 Waiting for server state to change to a non-null value
```

**Comment by adietish** [comment]
@odockal added fixes for MacOS (increased publishing timeouts) and made sure tests can be run individually. Please review.

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
+1. Ready to merge!

**Pull request merged**
