### PR TITLE
Add sonar profile in parent POM (parent POM formating) (fixes #234)

### LINKED ISSUE #234: use sonar for code inspection (replace codecov)
We currently use codecov to monitor test coverage. We should move over to sonar since it's far superior and provides far more indicators (test coverage, code smells, etc.).
@bdshadow prepared this (look here: https://sonarcloud.io/dashboard?id=org.jboss.tools.rsp%3Aparent) but didn't have the time to finish it.

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

### CODE REVIEW

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by robstryker** [comment]
testPR

**Pull request merged**
