### PR TITLE
Update to allow overriding cdk program args and environment

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

### CODE REVIEW

**Comment by robstryker** [comment]
A critical error has been discovered in how a Server object is translated into json, specifically when having two property keys that have maps as values. In short, it handles it very badly. 

For example, the following code:
```
HashMap<String,String> map1 = new HashMap<>();
map1.put("key1", "val1");
HashMap<String,String> map2 = new HashMap<>();
map2.put("wonka", "bear");
server.put("attribute1", map1);
server.put("attributeWonka", map2);
```

yields the incorrect json as follows:
  "map": {
    "key": "attribute1",
    "key1": "val1",
    "wonka": "bear"
  },

This is obviously incorrect and will need to be fixed before we can allow any server properties that expect maps to be created.

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@robstryker It seemed that PR check failed due to wildfly server error in some stage of itests execution. Not the itests failure but test error. Windows are somehow tricky it this.

**Comment by robstryker** [comment]
code smells are required in superclass. Override method must have them even if ti doesn't use them.  Patch looks good.

**Pull request merged**
