### PR TITLE
Adding API to methods that have no status field in response

### PR DESCRIPTION
**Pull request by robstryker**
This will break clients.

### CODE REVIEW

**Comment by robstryker** [comment]
testPR

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@robstryker I might have a suggestion, couldn't we have the response object returning from the server more generic? I mean, you are implementing response for each kind of object (list of deployable, deployable options, etc) that returns back from the server, all having status attribute in its body, wouldn't it be easier to have defined generic class for response, with status handling and having generic type for the objec it handles, or maybe wrapping response class with underlying data object?

Ie.:
```
public class Response<T> {
	
	T responseObj;
	Status status;
	
	public Response(T response, Status status) {
		this.responseObj = response;
		this.status = status;
	}
	
	public Status getStatus() {
		return status;
	}
	
	public T getResponseObj() {
		return responseObj;
	}
```
wdyt?

**Comment by odockal** [comment]
Anyway, I have updated test (to count with response object) and it seems fine, except: https://github.com/redhat-developer/rsp-server/blob/master/distribution/integration-tests/src/test/java/org/jboss/tools/rsp/itests/wildfly/WildFlyPublishingTest.java#L140, invalid publish request (sending some random int) it passing, should be returning status error, or similar, right?

**Comment by robstryker** [comment]
@odockal  I prefer not to use some weird heirarchy or generics in this API. We are generating the typescript rsp-client and I'd rather avoid anything confusing in that regard, even if it means a bit of code duplication. 

I will review wildfly publishing test.

**Comment by robstryker** [comment]
Fixes #409

**Pull request merged**
