### PR TITLE
Fix major sonar issues

### PR DESCRIPTION
**Pull request by bdshadow**

### CODE REVIEW

**Comment by robstryker** [comment]
@bdshadow   Can you please explain the point of this PR?  If it's to configure sonar, why are there so many changes to .java files? 

What are the java changes? Is it just code-cleanup? Are there bug-fixes or actual errors being fixed? Can we split this up into 3 separate PRs please?

1) configure sonar
2) Code cleanup / code-smell / etc
3) Actual bugs being fixed

**Comment by bdshadow** [comment]
There's a change in pom.xml, which allows to see the code coverage the same way we do it in jbosstools.
All issues and code smells are fixed according to the report here: https://sonarcloud.io/dashboard?id=org.jboss.tools.rsp%3Aparent. I fixed all such issues that gave our project rating D and E. There is still a lot to do to make it at least B.
I can split this up. It makes no sense to split it into 3 parts - 2 are enough. If we don't agree to have code coverage report from sonarcloud - it'll still be only one PR, i'll just rename it

**Comment by robstryker** [comment]
I suggest splitting this into two and rebasing it.

**Comment by bdshadow** [comment]
i think code coverage by sonar doesn't make sense, because we already have it by codecov. That's only this PR is provided by changing its name and rebasing the commit

**Comment by bdshadow** [comment]
is there any chance of this PR to be merged?

**Pull request merged**
