### PR TITLE
[86] Unify target platform and distribution dependencies

### PR DESCRIPTION
**Pull request by adietish**
this implements #86

### CODE REVIEW

**Comment by robstryker** [comment]
Is this done? Or does it still require the wait-for-bundle-to-be-loaded stuff? I tested it and it doesn't seem to function as-is.  I still get the NPEs.

**Comment by adietish** [comment]
@robstryker the fix for the bundle NPE's is not included yet, nor is the switch to the bundles in locus (move to locus is in a separate PR, once they're in this PR will be updated).

**Comment by jeffmaury** [comment]
Works for me but when I connect the CLI I got this error:

```
Client 127.0.0.1:55272 is connected                                                                                             
oct. 15, 2018 3:02:11 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError                                         
GRAVE: Unable to invoke no-args constructor for class org.jboss.tools.rsp.api.dao.ClientCapabilitiesRequest. Register an Instanc
ay fix this problem.                                                                                                            
java.lang.RuntimeException: Unable to invoke no-args constructor for class org.jboss.tools.rsp.api.dao.ClientCapabilitiesRequest
 Gson for this type may fix this problem.                                                                                       
        at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:226)                        
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)       
        at com.google.gson.Gson.fromJson(Gson.java:887)                                                                         
        at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.fromJson(MessageTypeAdapter.java:298)                     
        at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.parseParams(MessageTypeAdapter.java:229)                  
        at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:115)                         
        at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:51)                          
        at com.google.gson.Gson.fromJson(Gson.java:887)                                                                         
        at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:113)                          
        at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:108)                          
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:187)                   
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)                           
        at org.jboss.tools.rsp.server.RSPServerSocketLauncher$CustomMessageProcessor.run(RSPServerSocketLauncher.java:109)      
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)                                                  
        at java.util.concurrent.FutureTask.run(Unknown Source)                                                                  
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)                                                    
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)                                                   
        at java.lang.Thread.run(Unknown Source)                                                                                 
Caused by: java.lang.UnsupportedOperationException: Cannot allocate class org.jboss.tools.rsp.api.dao.ClientCapabilitiesRequest 
        at com.google.gson.internal.UnsafeAllocator$4.newInstance(UnsafeAllocator.java:104)                                     
        at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:223)                        
```

**Comment by adietish** [comment]
this PR will be updated once https://github.com/jbosstools/jbosstools-locus/pull/61 gets the additional bundles into locus.

**Comment by adietish** [comment]
@jeffmaury I see the same: 
```
SEVERE: Unable to invoke no-args constructor for class org.jboss.tools.rsp.api.dao.ClientCapabilitiesRequest. Register an InstanceCreator with Gson for this type may fix this problem.
java.lang.RuntimeException: Unable to invoke no-args constructor for class org.jboss.tools.rsp.api.dao.ClientCapabilitiesRequest. Register an InstanceCreator with Gson for this type may fix this problem.
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:226)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.fromJson(MessageTypeAdapter.java:298)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.parseParams(MessageTypeAdapter.java:229)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:115)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:51)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:113)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:108)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
	at org.jboss.tools.rsp.server.RSPServerSocketLauncher$CustomMessageProcessor.run(RSPServerSocketLauncher.java:109)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException: Cannot allocate class org.jboss.tools.rsp.api.dao.ClientCapabilitiesRequest
	at com.google.gson.internal.UnsafeAllocator$4.newInstance(UnsafeAllocator.java:104)
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:223)
	... 17 more

Client localhost:60172 is connected
Oct 15, 2018 5:34:43 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: Unable to invoke no-args constructor for class org.jboss.tools.rsp.api.dao.ClientCapabilitiesRequest. Register an InstanceCreator with Gson for this type may fix this problem.
java.lang.RuntimeException: Unable to invoke no-args constructor for class org.jboss.tools.rsp.api.dao.ClientCapabilitiesRequest. Register an InstanceCreator with Gson for this type may fix this problem.
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:226)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.fromJson(MessageTypeAdapter.java:298)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.parseParams(MessageTypeAdapter.java:229)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:115)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:51)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:113)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:108)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:90)
	at org.jboss.tools.rsp.server.RSPServerSocketLauncher$CustomMessageProcessor.run(RSPServerSocketLauncher.java:109)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException: Cannot allocate class org.jboss.tools.rsp.api.dao.ClientCapabilitiesRequest
	at com.google.gson.internal.UnsafeAllocator$4.newInstance(UnsafeAllocator.java:104)
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:223)
	... 17 more
```

@robstryker any idea?

**Comment by jeffmaury** [comment]
The `ClientCapabilitiesRequest` class is probably missing an empty constructor in order to be deserialized. Also some setters are missing?

**Comment by adietish** [comment]
@jeffmaury error exists in master, too. fixed it here: https://github.com/redhat-developer/rsp-server/pull/98

**Comment by adietish** [comment]
@robstryker @jeffmaury btw. regarding the problem with the starting order server/extenders: if properly done with services there would be no additional code in the extenders, they would register as services and the server would look them up (and watch them). Imho that's the better solution.

**Comment by robstryker** [comment]
I somehow broke this PR. That's my bad. 

I'm now stealing Andre's work and merging the identical PR over here:  https://github.com/redhat-developer/rsp-server/pull/99

**Comment by robstryker** [comment]
#99 is merged. So this is done.

**Pull request closed without merging**
