### PR TITLE
Changes in sonar quality profile for code coverage (fixes #369)

### LINKED ISSUE #369: sonar: currently reports 0% test coverage
[Sonarcloud](https://sonarcloud.io/dashboard?id=org.jboss.tools.rsp%3Aparent) currently reports 0% test coverage. 
image
We should find out why this happens and correct it.

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

### CODE REVIEW

**Comment by adietish** [comment]
@jkopriva looks like this should be fixing #369, correct?

**Comment by jkopriva** [comment]
@adietish yes!

**Comment by adietish** [comment]
@jkopriva awesomeness! Maybe a few words what the problem was and how solved it? I'd appreciate it a lot.

**Comment by jkopriva** [comment]
@adietish There were changes in sonar api: as you remember replace deprecated 'sonar.jacoco.reportPaths' by 'sonar.coverage.jacoco.xmlReportPaths'. So I have changed this to sonar.coverage.jacoco.xmlReportPaths(in previous PR), which broke coverage, but other stuff was working on sonar. I have not notice there are some settings related to jacoco plugin in integration tests, which were not compatible with new approach. Sonar is working quite good with default parameters, so I have used mostly defaults. I have had also an issue with mac: I am getting in rsp-server project 0% coverage with jacoco, but I get correct coverage on Fedora - I am still looking into it.

**Pull request merged**
